<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <base href="default/" />
        <script src="/scripts/swfobject.js" type="text/javascript"></script>
        <script src="/scripts/mootools.js" type="text/javascript"></script>                
        <script src="/scripts/Ferengi.Pxp.Feed.js" type="text/javascript"></script>
        <link href="/App_Themes/Fibertel2/Ajax.Default.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/barraHome.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/formContact.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/formRegistrationPopup.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/formsuscripcion.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/formsuscripcion_cv.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/jd.gallery.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/layout.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/mvc_promotion.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/mvc_registration.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/ReMooz.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/smoothbox.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/style.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/style.formRecomendar.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/style.ie.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/style.menu.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/style.structureanchocompleto.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/style.suscripcion.callejero.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/style_mvc.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/stylePopup.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/stylePopup.Grisado.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/ToolTips.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/ui-fibertel/jquery-ui.css" type="text/css" rel="stylesheet" /><link href="App_Themes/Fibertel2/WebMailBox.css" type="text/css" rel="stylesheet" /><title>
        </title></head>
    <body class="MasterPagePopup">		
        <form name="aspnetForm" method="post" action="ContentPopup.aspx?id=1190" id="aspnetForm">
            <div>
                <input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTE2NzkzNjUyODdkGAIFGmN0bDAwJGN0bDAyJE12U2NyaXB0R29vZ2xlDw9kAgFkBRxjdGwwMCRDb250ZW50UGxhY2VIb2xkZXIxJE1WDw9kZmQ=" />
            </div>
            <script>document.getElementById("aspnetForm").action = location.href;</script>
            <div class="ContentPopup">
                <div class="box">
                    <div class="header"></div>        
                    <div class="content S">
                        <div class="titulo">
                            <h1>Términos y Condiciones</h1>
                        </div>
                        <div class="imagenes"></div>
                        <div class="descripcion">
                            <P align=center>
                                <STRONG>TÉRMINOS Y CONDICIONES DE LA PRESTACIÓN DEL SERVICIO DE ACCESO A INTERNET FIBERTEL ZONE<BR>
                                </STRONG>
                            </P>

                            <P><STRONG>I. DEFINICIONES PREVIAS<BR>
                                </STRONG>
                                1. Toda prestación de servicios de acceso a la red Internet provistos por Primera Cablevisión S.A. (en adelante el "Servicio"), es regulada por los presentes términos y condiciones (en adelante "los términos y condiciones"). 
                                2. Los presentes términos y condiciones (que se encuentran alojados en el sitio web de Fibertel denominado www.fibertel.com.ar) se considerarán aceptados por el cliente mediante la conformidad que brinde el mismo al aceptarlos antes de comenzar a utilizar el Servicio en el lugar en donde se encuentren conforme el siguiente link: www.fibertel.com.ar
                                Las presentes Condiciones del Servicio, y las Condiciones Particulares de Servicio, si las hubiere, constituyen el acuerdo completo entre Fibertel y el Cliente con respecto a todo lo previsto en ellos, y sustituye cualquier comunicación o propuesta anterior o contemporánea, oral o escrita entre las partes respecto de su contenido.
                                3. A los efectos de la prestación del Servicio denominado Fibertel Zone existirán dos tipos de Clientes que harán uso del Servicio: 1) Aquellas personas que al momento de hacer uso de Fibertel Zone son Clientes activos y actuales de alguno de los productos de acceso a Internet Fibertel que brinda Cablevisión y 2) Aquellas personas que al momento de hacer uso de Fibertel Zone no sean Clientes activos y actuales de alguno de los productos de acceso a Internet Fibertel que brinda Cablevisión.
                            </P>
                            <P><STRONG>II. EL CLIENTE<BR>
                                </STRONG>
                                1. A los efectos de los presentes términos y condiciones, el Cliente es aquella persona física que utiliza el Servicio que brinda Fibertel a través de su producto denominado Fibertel Zone en el local comercial en el cual se encuentre ubicado.
                                2. La condición de Cliente es personal e intransferible, no pudiendo cederse a terceras personas sin el expreso consentimiento de Fibertel.
                                3. Para el servicio Fibertel Zone que brinda Cablevisión, este le podrá solicitar al Cliente seleccionar un nombre de usuario y una contraseña, quedando bajo su exclusiva responsabilidad mantener la confidencialidad de las mismas y de todo uso realizado con ellas, siempre que ya sea cliente actual de alguno de los productos de acceso a Internet que brinda Fibertel, en caso de que el Cliente no sea cliente actual de alguno de los productos de acceso a Internet de Fibertel este deberá suministrarle a Cablevisión los siguientes datos para poder hacer uso de la red de Fibertel Zone: cuenta de correo electrónico.
                                4. En caso de utilización del Servicio por terceros, el Cliente deberá instruirlos adecuadamente y responderá frente a Cablevisión por el mal uso del mismo, entendiéndose por tal toda contravención a lo establecido en los presentes términos, en la normativa legal vigente, la moral, las buenas costumbres generalmente aceptadas y/o el orden público. En tal supuesto, Cablevisión podrá reclamar los daños y perjuicios irrogados.
                            </P>
                            <P><STRONG>III. DURACIÓN<BR>
                                </STRONG>
                                1. La vigencia del servicio comenzará con su aceptación por parte del Cliente, de acuerdo a lo establecido en el punto I. 2 y se extenderá por plazo indeterminada mientras dure la sesión de dicho Cliente en el local comercial. 
                                2. Cablevisión podrá establecer nuevas condiciones y/o modificaciones a cualquiera de las cláusulas contenidas en los presentes términos y condiciones. Dichas modificaciones entrarán en vigencia a partir de su publicación en el sitio web denominado www.fibertel.com.ar. Las modificaciones que se efectúen a los presentes términos se considerarán aceptadas por el Cliente cuando las acepte mediante el acto positivo de confirmarlas antes de iniciar se sesión para hacer uso del Servicio. 
                                3. Cablevisión podrá poner fin a la presente, y consecuentemente a la relación que vincula a las partes, sin causa justificada.
                            </P>
                            <P><STRONG>IV. PRECIO<BR>
                                </STRONG>
                                El servicio de Fibertel Zone se prestara sin cargo alguno para los Clientes que lo utilicen dentro de los locales comerciales habilitados por Cablevisión para tal fin, sean o no Clientes de Fibertel activos al momento del uso.
                            </P>
                            <P><STRONG>V. CONDICIONES DE USO<BR>
                                </STRONG>
                                1. El Cliente tendrá derecho a la utilización del Servicio, responsabilizándose del contenido de la información que transfiera, descargue, publique o almacene a través de la red que utiliza, y se obliga a consultar en forma periódica las normas de Cablevisión relativas al uso del Servicio que forman parte de los presentes términos y condiciones. 
                                2. La red de Cablevisión puede ser utilizada únicamente con fines lícitos. Se encuentra expresamente prohibido todo uso, fijación, reproducción, transmisión y distribución de cualquier material protegido por el derecho de autor, marcas registradas o no, secretos comerciales, patentes u otros derechos de propiedad intelectual, sin la debida autorización por escrito de los respectivos autores y propietarios de las obras, como asimismo la publicación y distribución de todo material obsceno, difamatorio o que constituya una amenaza o contraríe las buenas costumbres, el orden público y/o la legislación vigente; Utilizar el Servicio para Spamming (envío indiscriminado de mensajes de correo electrónico a personas que no lo solicitan, con fines de publicidad, propaganda u otros), u otro tipo de mensajes molestos; difamar, abusar, acosar, hostigar, amenazar o de otra forma infringir los derechos de otras personas; Cargar archivos que contengan software u otro material que contengan virus, troyanos, gusanos, sistemas de cancelación de exposiciones (cancelbots), bombas de tiempo, archivos dañados, o cualquier otro programa o software similar que pueda perjudicar el funcionamiento de los equipos de terceros; Falsificar o eliminar atribuciones de autoría, avisos legales, designaciones o etiquetas de propiedad en el origen o en la fuente del software u otro material contenido en un archivo; Restringir o inhabilitar a otros usuarios la utilización de sus servicios y/o accesos; Infringir cualquier código de conducta u otras instrucciones que sean aplicables para cualquier servicio o acceso en particular; recoger o recopilar, sea en forma sistemática o no y sin autorización, información acerca de terceros, incluidas direcciones de correo electrónico; Crear una identidad falsa con el propósito de confundir a terceros; Utilizar, descargar o de otra manera copiar o proporcionar a terceros (con o sin fines de lucro), cualquier directorio o información de los usuarios de los sitios web; Infringir alguna ley, decreto, resolución o cualquier otra norma legal aplicable;
                                3. El Cliente responde por el buen uso de la conexión, comprometiéndose expresamente evitar realizar cualquier tipo de acción que pueda dañar sistemas, equipos; servicios accesibles o sitios web, directa o indirectamente a través del Servicio y de acuerdo con las normas contenidas en el presente documento. Sin perjuicio de ello, el Cliente declara conocer y poseer, todos los requerimientos técnicos necesarios para la compatibilidad de la provisión del Servicio con sus propios equipos.
                                4. El Cliente reconoce que las características propias de la red Internet, del Servicio y de los sistemas operativos de las computadoras y/u otro tipo de dispositivos, permiten compartir recursos (impresoras, discos rígidos, etc.) entre los usuarios de la red Internet. Asimismo, el Cliente declara conocer las medidas de seguridad que impiden compartir dichos recursos. En consecuencia, el Cliente exime de toda responsabilidad a Cablevisión en caso de que aquél comparta tales recursos y que de dicha actividad derive algún daño directo o indirecto para el Cliente o para terceros. 
                                5. El Cliente reconoce que Cablevisión no puede ejercitar control sobre el contenido de la información que circula a través de la red. Por este motivo, Cablevisión no es responsable de los contenidos que circulan por su red, independientemente si el envío fue hecho o no por un Cliente de Cablevisión.
                                Dado que la red de Cablevisión puede utilizarse para conectar con otras redes el Cliente acuerda cumplir y respetar las Políticas de Uso Aceptable de dichas redes. 
                                El Cliente acuerda cumplir con los protocolos y los estándares de Internet. Para más información ver http://www.usenet.org.
                                6. El Cliente realizará sus máximos esfuerzos para aplicar ciertas configuraciones, en su computador personal y cualquier otro dispositivo que utilice con acceso a Internet, que pudieran ser requeridas por Cablevisión para el correcto uso del Servicio.
                                7. El Cliente acepta y reconoce que los recursos técnicos de la red están dimensionados de acuerdo a la velocidad y capacidad de cada uno de los tipo de servicios, por ende, la utilización extrema del mismo puede producir un exceso sobre este dimensionamiento, por ende Cablevisión podrá exigir al cliente que adecúe su uso o contrate otro servicio superior. En caso de detectarse una utilización abusiva de los recursos de red que afecten o atenten el servicio de otros clientes, Cablevisión podrá suspender el servicio de dicho cliente en forma preventiva.
                                Cablevisión establece para el servicio de Fibertel Zone una cuota mensual de 2GB para actuales clientes de alguno de los productos de acceso a Internet Fibertel que brinda Cablevisión y una cuota mensual de 500M para aquellas personas que al momento de utilizar Fibertel Zone no poseen activo ningún producto de acceso a Internet Fibertel que brinda Cablevisión.
                                El Cliente acepta y reconoce la existencia de dichas cuotas fijadas para el uso del Servicio.
                                8. El Cliente se obliga al mantenimiento del soporte informático imprescindible para el acceso a la red, y de todo lo referente a la seguridad de los equipos que se utilicen tanto desde el punto de vista del hardware (puesta a tierra, etc.), cuanto del software.
                                9. La violación de seguridad a redes, sistemas o sitios web que en ellas se encuentren, están prohibidas. Estas acciones pueden originar una medida legal de Cablevisión en contra de sus autores.
                                Cablevisión investigará en base a las denuncias recibidas a través de los canales habilitados para tal fin y cualquier otra vía lícita, las violaciones a los sistemas o redes. Cablevisión se reserva el derecho de interrumpir provisoriamente el servicio mientras realiza la investigación pertinente.
                                Cablevisión considera -entre otras- violación de seguridad a redes, sistemas o sitios web a los siguientes supuestos:
                                i) El acceso no autorizado a datos, recursos, sistemas, sitios web o redes, cualquier intento de verificar la existencia de vulnerabilidades, o la violación de medidas de seguridad y autentificación, mediante intrusión u obtención de contraseñas por algún medio ilegítimo.
                                ii) El monitoreo no autorizado de datos o de tráfico de cualquier red o sistema sin la correspondiente autorización del propietario. 
                                iii) La interferencia con el servicio de cualquier usuario, huésped o red, incluyendo, sin limitación alguna mailbombing, flooding y ataques de denegación de servicio (DoS). 
                                iv) La falsificación de cualquier encabezado del protocolo TCP/IP o de cualquier información contenida en los encabezados de los correos electrónicos o grupos de noticias.
                                v) Las acciones que de algún modo pudieran dañar, deshabilitar, sobrecargar, deteriorar o interferir con el uso o disfrute de cualquier  sitio web, servicio o las redes conectadas a ellos.
                                10. Todo contenido o software disponible para verlo y/o descargarlo en conexión con los sitios web de Cablevisión o con los Servicios, excluyendo el contenido y/o software puesto a disposición por otros usuarios, es propiedad de Cablevisión o de sus proveedores, y se encuentra protegido por las leyes de propiedad intelectual.
                                11. El servicio de acceso a internet de Fibertel Zone no incluye los sitios web y/o su contenido ya sean éstos de Cablevisión o terceros. Cablevisión o sus respectivos proveedores pueden hacer modificaciones o mejoras en los sitios web en  cualquier momento, sin que ello implique incumplimiento alguno a las condiciones en que se presta el servicio de acceso a internet.
                            </P>
                            <P><STRONG>VI. OBLIGACIONES DE Cablevisión<BR>
                                </STRONG>               
                                1. Mantenimiento de las instalaciones necesarias para el funcionamiento del acceso a la red Internet, con un equipo técnico e informático adecuado.
                                2. No ejercerá ningún control sobre el contenido de la información que circule por sus redes salvo requerimiento de autoridad u organismo competente.
                            </P>
                            <P><STRONG>VII. MANTENIMIENTO DE SECRETO Y PROTECCIÓN DE DATOS<BR>
                                </STRONG>
                                El Cliente conoce y acepta que: (1) como consecuencia de la contratación de los servicios y con el fin de su prestación, Cablevisión y/o quien ésta designe expresamente a tal efecto podrá requerirle determinada información que puede ser considerada como ?Datos Personales? en virtud de lo dispuesto por la ley 25.326 (Protección de Datos Personales); (2) Cablevisión podrá contratar a una empresa para la prestación del servicio de almacenamiento, ordenación, modificación, evolución, bloqueo y en general el procesamiento de los Datos Personales.
                                Asimismo, y en cumplimiento de la ley 25.326 y las disposiciones dictadas por la Dirección Nacional de Protección de Datos Personales, se informa al Cliente que: (i) el titular de los Datos Personales tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita a intervalos no inferiores a seis meses, salvo que se acredite un interés legítimo al efecto conforme lo establecido en el artículo 14, inciso 3 de la ley 25.326; (ii) toda persona tiene derecho a que sean rectificados, actualizados y, cuando corresponda suprimidos o sometidos a confidencialidad los Datos Personales de los que sea titular, que estén incluidos en un banco de datos (artículo 16 de la ley 25.326); (iii) el titular podrá en cualquier momento solicitar el retiro o bloqueo de su nombre de los bancos de datos; (iv) La DIRECCION NACIONAL DE PROTECCION DE DATOS PERSONALES, Órgano de Control de la Ley N° 25.326, tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las normas sobre protección de datos personales (Artículo 2 de la Disposición 10/08 de la Dirección Nacional de Protección de Datos Personales). 
                                Para el ejercicio de dichos derechos de acceso, rectificación, actualización, bloqueo o supresión, el titular de los Datos Personales deberá presentarse en cualquiera de las sucursales de Cablevisión y previa acreditación de identidad deberá completar el formulario que allí le será provisto a tal efecto o mediante correo a datospersonales@cablevisión.com.ar  
                                Cablevisión podrá, con autorización expresa del Cliente o en virtud de una imposición legal y/o requerimiento librado por autoridad competente, de acuerdo con las normas internacionalmente reconocidas, comunicar datos de aquél o relativos a su utilización del servicio. 
                            </P>
                            <P><STRONG>VIII. LIMITACIÓN DE RESPONSABILIDAD<BR>
                                </STRONG>
                                1. Cablevisión y el Cliente serán cada uno responsables de la verificación y del control de la faz técnica y operativa de sus respectivas facilidades.
                                2. La responsabilidad de Cablevisión en cualquiera de los casos de incumplimiento imputables a ella estará limitada al importe equivalente a un abono mensual del Servicio de 6 megas de acceso a Internet Fibertel que brinda Cablevisión vigente a la fecha del incumplimiento.
                                3. Dado que la prestación del Servicio de Cablevisión depende también de recursos y servicios contratados con terceros, Cablevisión declina toda responsabilidad por los daños o perjuicios causados por hechos que emanen de aquéllos. Cablevisión no será responsable por errores de encaminamiento, pérdida de información o datos, retraso en la entrega o interrupciones del Servicio no planificadas, que no sean atribuibles a Cablevisión.
                                4. Cablevisión declina toda responsabilidad relacionada con la calidad, exactitud, fiabilidad y corrección de los datos, programas e información de cualquier tipo que circulen por sus redes (virus, programas en mal estado, utilización indebida de software, etc.). El contenido de dicha información es de exclusiva responsabilidad de los sujetos que la intercambien (remitente y destinatario). Cablevisión no responderá en caso de utilización del Servicio por terceros no autorizados.
                                5. El Cliente exonera a Cablevisión de todo reclamo judicial y/o extrajudicial motivado por acción u omisión del Cliente, sus clientes, contratistas, agentes o empleados, respecto del uso de las facilidades, redes y/o sistemas de telecomunicaciones de terceros, de un modo no contemplado o prohibido por el presente documento; como también de aquellos derivados directa o indirectamente de la interrupción o corte del Servicio prestado a través de las facilidades, redes y sistemas de terceros o por problemas de los mismos; por interrupción, sea ésta o no programada, de energía eléctrica o de algún otro servicio o medio que intervenga para el funcionamiento del mismo; asimismo, Cablevisión no será responsable frente al Cliente por daños y/o perjuicios que cualquier causa, incluyendo el caso fortuito o fuerza mayor, pudieran producirse a los equipos o instalaciones del Cliente y/o de terceros.
                                6. En ningún caso Cablevisión será responsable por daños indirectos, lucro cesante, ni pérdidas o daños de cualquier naturaleza vinculados con la actividad profesional o comercial del Cliente.
                            </P>
                            <P><STRONG>IX. RESPONSABILIDAD DEL CLIENTE<BR>
                                </STRONG>
                                El Cliente asume plena responsabilidad frente a Cablevisión y a terceros por los daños y perjuicios de toda clase, que puedan generarse como consecuencia del accionar propio, de sus dependientes o de terceros, vinculados al Servicio; así como de los derivados de los equipos, medios o sistemas de los que ellos se sirvan, y los daños que resulten de la inobservancia de las leyes o reglamentaciones, o de otros hechos ilícitos, debiendo  el Cliente indemnizar y mantener indemne a Cablevisión ante cualquier reclamo que pudiera corresponder en los supuestos indicados. 
                            </P>
                            <P><STRONG>X. CONDICIONES FINALES<BR>
                                </STRONG>
                                1. Cada cláusula de estos términos y condiciones es válida en sí misma y no invalidará al resto. La cláusula inválida o incompleta podrá ser sustituida por otra equivalente y válida por acuerdo de las partes.
                                2. La omisión en el ejercicio de alguna de las facultades o derechos conferidos por el presente instrumento no constituirá una renuncia a ninguna de las previsiones del mismo. 
                                3. Para el supuesto de controversias suscitadas en ocasión de los presentes términos y condiciones, Cablevisión constituye domicilio en Gral. Hornos 690 de la Ciudad Autónoma de Buenos Aires donde se tendrán por válidas y eficaces todas las comunicaciones, intimaciones, notificaciones y/o emplazamientos judiciales o extrajudiciales a que hubiere lugar con motivo del mismo, hasta tanto se comunique fehacientemente la constitución de uno nuevo. Tanto el Cliente como Cablevisión se someten voluntariamente a la jurisdicción y competencia de los Tribunales Nacionales Ordinarios con asiento en la Ciudad Autónoma de Buenos Aires, renunciando expresamente a cualquier otro fuero o jurisdicción que pudiera corresponder. La competencia aplicable a los CLIENTES cuyo domicilio se encuentre fuera de la Ciudad Autónoma de Buenos Aires al momento de la contratación, será la correspondiente a tal domicilio.
                            </P>
                            <P><STRONG>XI. <BR>
                                </STRONG>
                                Cablevisión se reserva el derecho a realizar la acción publicitaria, de prensa, promoción, publicación y difusión que considere conveniente de los datos proporcionados por los Clientes que hagan uso del servicio de Fibertel Zone. Con la sola proporción de datos y aceptación de los presentes términos y condiciones, los Clientes prestan su expresa conformidad para la utilización y difusión de sus Nombres y Tipo y Nº de Documento e Imágenes (foto y voz) por los medios publicitarios y de comunicación que Cablevisión S.A. disponga.  La presente autorización es realizada en los términos del artículo 1071 bis del Código Civil, del artículo 11 del Pacto de San José de Costa Rica, del artículo 31 de la Ley N° 11.723, del art. 3, inc. h) de la Ley N° 22.362 y toda otra normativa concordante. En virtud de esta autorización, los Clientes no tendrán derecho a indemnización, pago o contraprestación alguna por la difusión y/o utilización mencionada precedentemente. Cablevisión no se responsabilizará por la autenticidad de los datos proporcionados por los Clientes en el acto de registración desde el portal de Fibertel Zone, o por el suministro de informaciones incorrectas, imprecisas e incompletas que imposibiliten la efectiva conexión. Los Clientes ceden asimismo a Cablevisión todos los derechos de autor y patrimoniales relativos al material enviado, que pasará a ser de propiedad de Cablevisión. La cesión de derechos de autor aquí referida incluye el derecho de Cablevisión, o terceros por él contratados, de reproducir el material enviado, preparar otros materiales utilizando el material enviado, combinar el material enviado con otros materiales, alterar, traducir, distribuir copias, exhibir, licenciar el material enviado o solicitar registro de derechos autorales en nombre de Cablevisión en cualquier parte de mundo, en cualquier medio actualmente conocido o creado a futuro.
                            </P>
                        </div>
                    </div>                
                    <div class="botones">
                        <a href="#" onClick="javascript:window.print();" class="bt_print">&nbsp;<span>imprimir</span></a>	
                    </div>        	
                    <style media="print">
                        .botones{display:none;}
                    </style>
                </div>
            </div>
            <script type="text/javascript">
                var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
                document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
            </script>
            <script type="text/javascript">
                try {
                    var pageTracker = _gat._getTracker("UA-15462396-1");
                    pageTracker._setDomainName(".fibertel.com.ar");
                    pageTracker._trackPageview();
                } catch (err) {
                }
            </script>
        </form>               
    </body>
</html>