<p>
</p><p><strong>REGOLAMENTO &nbsp;COPPA CALCIOTTO - SUMMER 2013</strong></p>
<p>&nbsp;</p>
<p><strong>Premessa:</strong></p>
<p>Il regolamento del&nbsp;<strong>COPPACALCIOTTO&nbsp;</strong>si rifà al&nbsp;<span>regolamento ufficiale DI GIUOCO della Federazione Italiana Giuoco Calcio (FIGC)</span>.<br>L'organizzazione del&nbsp;<strong>COPPACALCIOTTO</strong><strong>&nbsp;</strong>cura&nbsp;<span>esclusivamente&nbsp;</span>la parte organizzativa del torneo.<br>E' giusto avvisare i partecipanti del torneo che, per quanto riguarda la parte "disciplinare", questo è compito dell'Ente Disciplinare<strong>&nbsp;</strong>la qual è l'unica responsabile di squalifiche, provvedimenti disciplinari e tutto ciò che riguarda l'arbitrato. L'ente&nbsp;<strong>&nbsp;</strong>attua il regolamento della&nbsp;<span>lega nazionale dilettanti.</span><br>L'organizzazione del&nbsp;<strong>TORNEOCALCIOTTO&nbsp;</strong>per questi motivi si tira fuori da qualsiasi questione disciplinare, se non per fare da tramite tra partecipanti ed Ente.</p>
<p>&nbsp;</p>
<p><strong>REGOLA 1 – ISCRIZIONE<br></strong>1) L’iscrizione complessiva è di 80€ per le squadre partecipanti alla 16°edizione, e di 120€ per le altre<br>2)Ogni squadra deve iscrivere un minimo di 8 giocatori. Può iscrivere nuovi tesserati fino alla fine della fase a girone&nbsp;<br>3)Nella quota d’iscrizione è compresa la somma di € 80,00 come costo di cauzione che gli sarà restituita a fine torneo se sarà eseguita nel modo corretto la REGOLA 6&nbsp;&nbsp;<br>4)Ogni squadra deve essere attrezzata con dei propri completi da gara. L’Organizzazione mette a disposizione speciali kit (maglia+pantalone+numeri) a € 10,00.<br><br><strong><br>REGOLA 2 - LIMITAZIONI GIOCATORI<br></strong>Al torneo possono partecipare<br>1)Non vi sono limiti di età o di tesserati</p>
<p><strong>REGOLA 3 – ISTRUZIONI PER L’ISCRIZIONE e MODULISTICA NECESSARIA<br></strong>L’Organizzazione del TORNEOCALCIOTTO consegnerà agli interessati una cartella con la modulistica necessaria all’iscrizione del TORNEO.</p>
<ol>
    <li><strong>REGOLAMENTO<br></strong>Contiene il regolamento stilato delle quattro categorie</li>
    <li><strong>MODULO D’ISCRIZIONE ALLA COPPACALCIOTTO</strong><br>-I campi richiesti dovranno essere compilati in modo leggibile.<br>-Serve all’Organizzazione per iscrivere i giocatori al COPPA e inserirli sul sito www.torneocalciotto.it</li>
    <li><strong>DOMANDA AMMISSIONE A SOCIO DELLA ASD AREND<br></strong>-I campi richiesti dovranno essere compilati in modo leggibile.<br>-Qualora il partecipante non abbia raggiunto la maggiore età dovrà esser firmato da un genitore. Allegare la fotocopia del documenta d’identità valido del genitore alla Liberatoria<strong><br></strong>-I campi richiesti dovranno essere compilati in modo leggibile.<br>-Permette la diffusione dei diritti di immagine e di quanto concerne i diritti di privacy</li>
    <li><strong>MODULO RICHIESTA DIVISE<br></strong>-I campi richiesti dovranno essere compilati in modo leggibile.<br>-Serve all’Organizzazione per ordinare le Divise richieste alla Sponsor Ufficiale del TORNEOCALCIOTTO</li>
    <li><strong>CATALOGO DIVISE</strong><br>-E’ strutturato in 3 offerte:<br>1)Set Free. Ogni squadra potrà acquistare 10 divise al costo di € 100,00. Le restanti costeranno € 10,00<br>2)Set Silver. Ogni squadra potrà acquistare 10 divise al costo di € 140,00. Le restanti costeranno € 14,00<br>3)Set Gold. Ogni squadra potrà acquistare 10 divise al costo di € 160,00. Le restanti costeranno € 16,00</li>
    <li><strong>SPONSORIZZA LA TUA SQUADRA<br></strong>Il seguente file può esser usato dalla squadra che intende iscriversi per cercare più agevolmente uno sponsor per la propria società</li>
</ol>
<p><strong>REGOLA 4 – DOCUMENTI D’IDENTITA’<br></strong>Al modulo dovranno essere allegate le fotocopie di un documento valido d’identità con fotografia:<br>1)di tutti i partecipanti della squadra<br>2)di tutti i dirigenti che si vorranno far scendere in campo durante la gara di tutti i partecipanti.</p>
<p><strong>I giocatori e i tesserati che non hanno consegnato il proprio documento non potranno scendere in campo</strong></p>
<p><strong><br>REGOLA 5 – L'AREND CARD<br>l'Arend Card&nbsp;</strong>è rilasciata ai partecipanti del TORNEO che avranno consegnato il proprio documento d’identità</p>
<p>L'Arend Card porterà i seguenti vantaggi ai possessori:<br>a)può essere presentata come documento d’identità all’atto del riconoscimento in campo prima della gara<br>b)può dare vantaggi con gli Sponsor della ASD AREND che avranno formulato particolari offerte per i Soci<br><strong><br><br>REGOLA 6 – LA CAUZIONE<br></strong>La cauzione sarà restituita al capitano della squadra il giorno seguente la conclusione del torneo SOLO se:<br>1) La squadra si sia sempre presentata al campo<br>2) Avrà pagato l'intera somma d’iscrizione nei termini stabiliti alla REGOLA 1<br>3) Avrà sempre pagato il costo totale del campo<br>4) Non avrà alcun debito (maglie, iscrizione calciottomercato ecc)</p>
<p>N.B. L’Organizzazione tratterrà il 20% dei debiti monetari di ogni squadra</p>
<p><strong>Le squadre che avranno superato il tetto della cauzione dovranno pagare in ogni caso un'ammenda di 80€.<br>Ogni squadra, infatti, all'atto dell'iscrizione ha prescritto di non avere il diritto di ritirarsi sino alla fine del torneo.</strong></p>
<p><strong>REGOLA 7 – CONSEGNA E TERMINI DI ISCRIZIONE E MODULO<br></strong>Per la consegna delle iscrizioni e del modulo potete scegliere tra le seguenti possibilità:</p>
<p>1)Consegnare in busta chiusa il modulo, le 10 (o più) fotocopie di carte d'identità, il modulo per la richiesta iscrizione ai soci, le liberatorie d’assicurazione, il modulo per le divise e la quota totale di iscrizione alla portineria di C.so Vittorio Emanuele n°42 aperta dalle ore 8.00 alle 19.00 (chiusa dalle 13 alle 16) intestata ad A.S.D.Arend<br>2)Inviare il modulo alla casella elettronica info@asdarend.it&nbsp;e in seguito stabilire un incontro con uno degli organizzatori per la consegna della quota d’iscrizione<br>3)Consegnare tutta la modulistica e la quota di iscrizione agli organizzatori che saranno disponibili a raccogliere le iscrizioni e a dare ulteriori informazioni agli interessati al Bar Michelangelo adiacente alla Cumana del C.so Vittorio Emanuele nei giorni che saranno resi noti sul sito www.asdarend.it o sul contatto Facebook</p>
<p><strong>REGOLA 8 – IL PRECAMPIONATO</strong></p>
<ul>
    <li>Il Precampionato del torneo inizierà lunedi 17 giugno 2013</li>
    <li>E’ possibile partecipare al Precampionato del COPPA per avere un’idea del COPPA solo avendo versato all’Organizzazione almeno metà della quota di iscrizione(compresa cauzione) per poi in seguito decidere se iscriversi.</li>
    <li>Ogni squadra ha il dovere di partecipare ad almeno una gara durante il precampionato, tesa a permettere all’Organizzazione di valutare la correttezza della squadra in campo</li>
    <li>Ogni squadra può inoltre richiedere di farsi inserire in più partite, anche nella stessa settimana, per testare la squadra contro altre compagini del torneo.</li>
    <li>A fine precampionato l’organizzazione diramerà la propria decisione sulle squadre che potranno partecipare.</li>
    <li>L'organizzazione si riserva il diritto di scegliere le squadre che parteciperanno al torneo secondo loro libera scelta.<br>Nel caso una squadra non venga scelta l'organizzazione consegnerà la somma di iscrizioni precedentemente anticipata<br><br><strong>L’organizzazione informa che si riserva il diritto di escludere, dopo il Precampionato, una società dal torneo per qualsiasi motivazione.<br>Nel caso la società sarà esclusa l’organizzazione consegnerà indietro la quota d’iscrizione precedentemente pagata.</strong></li>
</ul>
<p><strong>REGOLA 9 – COMPONIMENTO DEL TORNEO</strong></p>
<p>&nbsp;</p>
<p>Le Iscrizioni alla CoppaCalciotto inizieranno il 15 giugno 2013.<br>E' formato da 7 gironi, ognuno da 4 squadre.<br>Prevederà 3 giornate con partite di sola andata.<br>Le prime due squadre accederanno ai quarti di finale.<br>Accederanno agli ottavi di finale anche le due migliori terze classificate.</p>
<p>&nbsp;In caso di squadre a paripunti in classifica si valuteranno nel seguente ordine:<br>1)Scontri diretti<br>2)Differenza reti<br>3)Maggior numero di gol<br>4)Minor numero di ammonizioni<br>5)Sorteggio alla presenza dei due capitani.</p>
<p>Per scegliere le due squadre migliori terze si valuteranno nel seguente ordine:<br>1)punti<br>2)differenza reti<br>3)maggior numero di gol<br>4)minor numero di ammonizioni<br>5)sorteggio alla presenza dei capitani&nbsp;</p>
<p>La fase finale inizieranno con gli ottavi di finale, con gara ad eliminazione diretta.<br>Anche le successive fasi prevederanno partite ad eliminazione diretta.</p>
<p>N.B.Potranno partecipare alle fasi finali delle competizioni solamente quei giocatori che avrà partecipato ad almeno 1 partita nella fase a gironi, avendo totalizzato almeno 10 minuti di permanenza in campo per ogni match.</p>
<p><br><strong>REGOLA 10 - CAMPO E GIORNI</strong><br>-Il torneo si svolgerà ai campi Millennium Football di Via Antiniana di Agnano (Pozzuoli) nei giorni:</p>
<p>Girone A:&nbsp;Lunedi: ore 18-19-20-21-22-23<br>Girone B: Martedi: ore 18-19-20-21-22-23<br>Girone C: Martedi: ore 18-19-20-21-22-23<br>Girone D: Mercoledi: ore 18-19-20-21-22-23<br>Girone E: Giovedi: ore 18-19-20-21-22-23<br>Girone F: Giovedi: ore 18-19-20-21-22-23<br>Girone G: Venerdi: ore 18-19-20-21-22-23</p>
<p>1) Al momento dell'iscrizione la squadra dichiara di essere disponibile a giocare in qualsiasi ora dichiarata al punto precedente<br>2) Al momento dell’iscrizione, inoltre, la squadra dovrà consegnare all’Organizzazione almeno due giorni(con orari) di preferenza<br>3) L'organizzazione non potrà cambiare il calendario o gli orari della partita se non per motivi insuperabili decisi in ogni modo sempre dall'organizzazione<br>4) Per poter spostare la partita (solo per motivi davvero importanti) la squadra dovrà comunicarlo all’Organizzazione 72 ore prima della partita<br>5)Il calendario, stipulato prima dell’inizio del torneo, comprenderà tutte le gare delle fasi finali. Ogni squadra potrà chiedere massimo 3 spostamenti, comunicandolo all’Organizzazione nel gruppo apposito “Capitani Torneocalciotto”</p>
<p><strong>REGOLA 11 – COSTO DEL CAMPO<br></strong>Il costo del campo è di €72,00 a squadra.<br>Ogni squadra ha il diritto di decidere in che modalità dividere il costo del campo con i propri giocatori.<br>Il pagamento del campo va compiuto tassativamente prima di scendere in campo nella segreteria della struttura, in caso contrario la partita non potrà iniziare.</p>
<p><strong>REGOLA 12 – VINCITA E PREMI</strong><strong><br><br></strong>La squadra vincitrice avrà diritto a partecipare al campionato nazionale del circuito 24H che si svolgerà a Cesenatico il 7 settembre 2013.</p>
<p>Il premio è coperto per 10 giocatori.<br>Nel premio è compreso il pernotto.<br>Non sono compresi eventuali costi di assicurazione, viaggio etc</p>
<p><strong>REGOLA 13 – CALCIOTTOMERCATO<br></strong>Il Calciottomercato aprirà il giorno seguente l’ultima partita dell’3 giornata sino al giorno prima della prima partita delle quarti.<br>Le squadre potranno effettuare il calciottomercato secondo le seguenti regole:<br><strong><br></strong>1)Potranno acquistare<br>- Nr. 2 di giocatori già iscritti al torneo in un'altra squadra&nbsp;<br>-Nr.1 di giocatori non iscritti al torneo o nella stessa lega</p>
<p>1)Ogni giocatore acquistato deve consegnare entro l’ultimo giorno dell’apertura del calciottomercato la propria fotocopia del documento d’identità o il giorno precedente del suo esordio al torneo<br>2)Ogni giocatore non può esser iscritto in più di due società per stagione</p>
<p>3)Gli acquisti vanno preannunciati almeno 24 ore prima dalla gara.<br>4)Per permettere a un acquisto di giocare è obbligatorio consegnare, prima della partita, la quota e il documento di identità. Non sarà possibile scalare tale cifra da eventuali cauzione<br>5)Ogni giocatore non può esser iscritto in più di due società per stagione</p>
<p>6)Le squadre che si saranno attivate nel calciottomercato dovranno provvedere al fornire i giocatori della divisa della squadra. Senza non potranno scendere in campo</p>
<p><strong>REGOLA 14 – ESCLUSIONE SQUADRA DAL TORNEO<br></strong>L'organizzazione si riserva il diritto di escludere la squadra dal torneo qualora:<br>1)Non si presenterà al campo più di due volte<br>2)Non si presenterà sul rettangolo di gioco entro 20 minuti dall'orario stabilito<br>3)Non pagherà il campo più di una volta<br>4)Sarà scoperto aver formato una squadra contro il regolamento stesso (giocatori fuoriquota, tesserati, carte d'identità false, etc.)<br>5)Aver superato con i debiti la quota di cauzione<br>Le partite successive della squadra esclusa saranno perse da questa col risultato di 3-0 a tavolino.</p>
<p><strong><br>REGOLA 15 – L’ARBITRO</strong></p>
<ol>
    <li><span>L'autorità dell'Arbitro</span><br>Per la direzione di ogni gara l’Ente Disciplinare deve designare un arbitro. La sua autorità e l'esercizio dei poteri che gli sono conferiti dalle Regole del Giuoco, iniziano nel momento in cui giunge nel luogo dove è ubicato il campo di giuoco e cessano quando se ne sia allontanato definitivamente.</li>
    <li><span>Poteri e compiti</span><br>L'Arbitro deve:<br>• applicare le Regole del Giuoco;<br>• permettere che il giuoco continui quando la squadra contro la quale è stata commessa un'infrazione, ne risulterebbe avvantaggiata e punire l'infrazione se il previsto vantaggio non si dovesse verificare;<br>• prendere nota dei fatti relativi alla gara e fornire alle autorità competenti un referto di gara che comprende le informazioni su qualsiasi provvedimento disciplinare preso nei confronti dei calciatori e/o dei dirigenti di squadra e su qualsiasi fatto e incidente occorso prima, durante o dopo la gara;<br>• svolgere le funzioni di cronometrista in assenza del cronometrista ufficiale;<br>• interrompere, sospendere o decretare la fine della gara a causa di qualsiasi infrazione delle Regole o di qualsiasi tipo di interferenza esterna;<br>• prendere provvedimenti disciplinari nei confronti di calciatori colpevoli di infrazioni punibili con l'ammonizione e l'espulsione;<br>• assicurarsi che non entrino nel rettangolo di giuoco persone non autorizzate;<br>• interrompere il giuoco se ritiene che un calciatore sia gravemente infortunato ed assicurarsi che venga trasportato fuori dal rettangolo di giuoco;<br>• lasciare proseguire il giuoco fino a quando il pallone cessa di essere in giuoco se, a suo avviso, un calciatore è lievemente infortunato;</li>
    <li><span>Decisioni dell'arbitro</span><br>Le decisioni dell'arbitro su fatti relativi al giuoco sono inappellabili.</li>
</ol>
<p><strong>REGOLA 16 – SPOSTAMENTO PARTITE<br></strong>In caso di problemi di qualsiasi natura l'organizzazione si riserva il diritto di anticipare, posticipare o annullare la gara previa comunicazione ai capitani delle squadre (o un membro di essa in caso di irreperibilità di quest'ultimo) anche il giorno stesso della partita.</p>
<p>In caso di maltempo la squadra è tenuta a presentarsi al campo, salvo diversa comunicazione da parte dell'organizzazione, lasciando all'arbitro la decisione di giocare o meno la partita.</p>
<p>Non è possibile per le squadre chiedere il rinvio di una gara.<br>Qualsiasi squadra che, per un qualsiasi motivo non è in grado di presentarsi sul campo, deve comunicarlo all'organizzazione entro 72 ore dalla data prevista per la partita.<br>In caso di comunicazione tardiva o mancata, la squadra dovrà pagare una penale di € 100 da consegnare entro 72 ore. Pena l'esclusione dal torneo. La penale non potrà essere attinta in nessun caso dalla cauzione</p>
<p>Ogni squadra avrà diritto a chiedere lo spostamento di una gara massimo tre volte in tutta la fase finale comunicandolo sul gruppo CALENDARIO TORNEOCALCIOTTO presente sulla Community Facebook entro e non oltre il mercoledi della settimana antecedente.<br>Superato il limite, dovrà inviare una mail ad info@asdarend<a href="mailto:asdarend@hotmail.it">.it</a>&nbsp;L’Organizzazione si prodigherà alla modifica. In caso positivo la società richiedente pagherà un ammenda di € 10,00.</p>
<p><strong>REGOLA 17 – DISTINTE E DIVISE</strong><br>Ogni squadra, come accennato nella REGOLA 1, deve avere una propria divisa.<br>Anche dopo la data del CALCIOTTOMERCATO i giocatori acquistati dovranno avere la medesima divisa sociale.<br>Inoltre, tutti i giocatori devono avere un numero riconoscitivo segnato dal Capitano nella distinta che dovrà consegnare all'arbitro prima della gara.</p>
<p>L'Organizzazione metterà a disposizione di tutte le squadre il pacchetto base per le divise, al prezzo di €100 e comprensivo di:<br>-10 kit da gioco (maglia + pantaloncino) + numerazione</p>
<p>Ogni divisa ordinata in più avrà un costo di €12,00.</p>
<p>Qualora una squadra volesse ricevere divise diverse da quelle messe a disposizione dovrà pagare una differenza di €50,00</p>
<p>Prima della gara l’Organizzazione consegnerà al Capitano della squadra la Distinta Ufficiale consegnata dallo stesso Capitano all’atto dell’iscrizione-<br><br>Sulla distinta il capitano deve compilare, in modo leggibile, i seguenti punti:<br>-deve segnare giorno e ora della gara<br>-deve segnare in modo chiaro Capitano e Vicecapitano<br>-deve apportare un puntino nell’apposita sezione all’altezza dei giocatori che scenderanno in campo<br>-sottoscriverla e firmarla</p>
<p>Coloro che non saranno segnati nella distinta potrebbero non poter seguire la partita da bordocampo a discrezione dell'arbitro.<br>inoltre sia i partecipanti che i dirigenti dovranno effettuare il riconoscimento con il proprio documento di identità valido o con la tessera socio</p>
<p>Tutta la squadra deve avere la stessa maglietta e ognuna dev'essere numerata.</p>
<p><strong>REGOLA 18 – RITARDI E DURATA DELLA GARA</strong><br>L'intera squadra deve presentarsi al campo con 30 minuti d'anticipo dalla partita</p>
<ol>
    <li><span>In caso di ritardi</span><br>• Il tempo massimo di attesa in campo è di 15 minuti. A partire dal 20 minuto, ogni 5 minuti d'attesa, comporteranno un gol di svantaggio per la squadra in ritardo. I gol non potranno non essere acquisiti dalla squadra presente sul campo e la gara non potrà comunque, in nessun caso, durare oltre i 10 minuti in più rispetto all'orario d'ufficio (Es.se la partita è programmata per le 22, e la gara inizia alle ore 22.30 la squadra in ritardo partirà con 3 reti di svantaggio e la gara durerà 40 minuti, dovendo terminare tassativamente pre le 23.10)</li>
    <li>Periodi di giuoco<br>• La durata della gara è stabilita in due periodi di 25 minuti effettivi di giuoco.</li>
    <li>L'intervallo di metà gara<br>• L'intervallo di metà gara non potrà superare i 5 minuti.</li>
</ol>
<p><strong>REGOLA 19 - CALCIO D'INIZIO E RIPRESA DEL GIUOCO</strong></p>
<ol>
    <li>Preliminari<br>• La scelta della metà del rettangolo di giuoco viene sorteggiata con una moneta. La squadra che vince il sorteggio sceglie la porta contro cui attaccherà nel primo periodo di giuoco. L'altra squadra ha diritto a battere il calcio d'inizio della gara.<br>• La squadra che vince il sorteggio ha diritto a battere il calcio d'inizio del secondo tempo della gara.<br>Nel secondo periodo della gara le squadre invertono le rispettive metà del rettangolo da giuoco ed attaccano in direzione della porta opposta.<br>•Ogni squadra deve far scendere in campo 6 giocatori. Si gioca con 8 giocatori per squadra</li>
    <li>Il calcio d'inizio<br>• Il calcio d'inizio è un modo di iniziare la gara o di riprendere il giuoco:<br>a) all'inizio della gara;<br>b) dopo che una rete è stata segnata;<br>c) all'inizio del secondo periodo di giuoco;<br>•Una rete può essere segnata direttamente su calcio d'inizio.</li>
    <li>Procedura<br>• La procedura per il calcio d'inizio è la seguente:<br>a) tutti i calciatori devono trovarsi nelle rispettive metà del rettangolo di giuoco;<br>b) i calciatori della squadra che non batte il calcio d'inizio devono posizionarsi ad una distanza di almeno m. 1 dal pallone fino a quando questo non sia in giuoco;<br>c) il pallone deve essere fermo al suolo nel punto centrale del rettangolo di giuoco;<br>d) l'arbitro emette il fischio che autorizza il calcio d'inizio;<br>e) il pallone è in giuoco quando viene calciato e si muove in avanti;<br>f) il calciatore che batte il calcio d'inizio non può toccare nuovamente il pallone prima che lo abbia toccato un altro calciatore;<br>g) quando una squadra segna una rete, il calcio d'inizio spetta all'altra squadra.</li>
    <li>Infrazioni e Sanzioni<br>• Se il calciatore che ha battuto il calcio d'inizio giuoca una seconda volta il pallone prima che questo sia stato toccato o giuocato da un altro calciatore dovrà essere accordato un calcio di punizione indiretto a favore della squadra avversaria, dal punto in cui è stata commessa l'infrazione.<br>• Per qualsiasi altra infrazione commessa nel battere il calcio d'inizio, quest'ultimo deve essere ripetuto.</li>
    <li>Rimessa in giuoco del pallone<br>• Dopo un'interruzione temporanea di giuoco provocata da una causa non prevista dalle Regole del Giuoco la gara deve essere ripresa con una rimessa in giuoco del pallone da parte dell'arbitro.</li>
    <li>Procedura per la rimessa in giuoco del pallone<br>• La procedura è la seguente:<br>a) l’ arbitro lascia cadere il pallone nel punto in cui si trovava al momento dell'interruzione, salvo che si tratti dell'area di rigore; in tale caso deve farlo cadere sulla linea dell'area di rigore, nel punto più vicino a quello in cui si trovava al momento dell'interruzione.<br>b) il giuoco riprende non appena il pallone tocca il suolo.</li>
    <li>Infrazioni e Sanzioni<br>• La rimessa del pallone deve essere ripetuta:<br>a) se il pallone viene toccato da un calciatore prima di entrare in contatto con il suolo;<br>b) se il pallone esce dal rettangolo di giuoco dopo il contatto con il suolo, senza essere stato toccato da un calciatore.</li>
</ol>
<p><strong>REGOLA 20 - PALLONE IN GIUOCO E NON IN GIUOCO</strong></p>
<ol>
    <li>Pallone non in giuoco<br>Il pallone non è in giuoco quando:<br>a) ha interamente oltrepassato, sia in terra sia in aria, una linea laterale o una linea di porta;<br>b) il giuoco è stato interrotto dall'arbitro;<br>c) tocca il soffitto.</li>
    <li>Pallone in giuoco<br>Il pallone è in giuoco in tutti gli altri casi ivi compreso quando:<br>a) rimbalza nel rettangolo di giuoco dopo aver colpito un palo o la sbarra trasversale della porta;<br>b) rimbalza su uno degli arbitri che si trova all'interno del rettangolo di giuoco.</li>
</ol>
<p><strong>REGOLA 21 - SEGNATURA DI UNA RETE</strong></p>
<ol>
    <li>Segnatura di una rete<br>Salvo le eccezioni previste dalle Regole del Giuoco, una rete risulta segnata quando il pallone ha interamente superato la linea di porta, tra i pali e sotto la sbarra trasversale, sempreché non sia stato lanciato, portato o colpito intenzionalmente con la mano o con il braccio da un calciatore della squadra attaccante, portiere compreso.</li>
    <li>Squadra vincente<br>La squadra che ha segnato il maggior numero di reti durante una gara, risulta vincente. Se non è stata segnata nessuna rete o se le squadre hanno segnato un eguale numero di reti, la gara risulta pari.</li>
    <li>Regole della competizione<br>Per le partite che si concludono in parità nelle fasi finali, le regole della competizione prevedono i calci di rigore senza tempi supplementari.</li>
</ol>
<p><strong>REGOLA 22 - FALLI E COMPORTAMENTO ANTISPORTIVO</strong></p>
<ol>
    <li>I falli ed i comportamenti antisportivi devono essere puniti come segue:<br>• Calcio di punizione diretto<br>Alla squadra avversaria viene accordato un calcio di punizione diretto quando un calciatore commette uno dei seguenti sei falli:<br>a) dare o tentare di dare un calcio ad un avversario;<br>b) fare o tentare di fare uno sgambetto all'avversario;<br>c) saltare su un avversario;<br>d) caricare un avversario, anche con la spalla;<br>e) colpire o tentare di colpire un avversario<br>f) spingere un avversario.<br>• Alla squadra avversaria viene accordato un calcio di punizione diretto anche quando un calciatore commette una delle seguenti infrazioni:<br>g) trattiene un avversario;<br>h) sputa contro un avversario;<br>i) tenta di giocare il pallone intervenendo in scivolata da tergo su un avversario che sia in possesso del pallone o che sia in procinto di giocarlo (contrasto da tergo scivolato). Questa norma non si applica al portiere che si trova nella propria area di rigore, purché egli non giochi in maniera imprudente, spericolata o con sproporzionata vigoria;<br>l) tocca deliberatamente il pallone con le mani. Questa norma non si applica al portiere che si trova nella propria area di rigore.<br>Il calcio di punizione diretto va battuto dal punto in cui è stato commesso il fallo.</li>
    <li>Calcio di rigore<br>Viene assegnato un calcio di rigore quando un calciatore commette uno dei suddetti falli all'interno della propria area di rigore, indipendentemente dalla posizione del pallone, purchè lo stesso sia in giuoco.</li>
    <li>Calcio di punizione indiretto<br>Alla squadra avversaria viene assegnato un calcio di punizione indiretto quando il portiere commette una delle seguenti infrazioni:<br>a) dopo essersi spossessato del pallone, lo riceve di ritorno da un compagno prima che abbia superato la linea mediana o senza che sia stato giocato o toccato da un avversario;<br>b) tocca o controlla il pallone con le mani (nella propria area di rigore) dopo che questo gli sia stato volontariamente passato con i piedi, da un compagno di squadra;<br>c) tocca o controlla con le mani (nella propria area di rigore) il pallone passatogli direttamente su una rimessa dalla linea laterale, effettuata da un compagno di squadra;<br>Alla squadra avversaria viene assegnato un calcio di punizione indiretto, che dovrà essere battuto dal punto in cui è stata commessa l'infrazione, anche quando, secondo il parere dell'arbitro, un calciatore:<br>d) giuoca in modo pericoloso;<br>e) impedisce intenzionalmente la progressione di un avversario senza che il pallone sia giocato;<br>f) ostacola il portiere nell'atto di liberarsi del pallone che ha tra le mani;<br>h) commette qualsiasi altra infrazione per la quale il giuoco viene interrotto per ammonire o espellere un calciatore.<br>Il calcio di punizione indiretto deve essere battuto nel punto in cui è stata commessa l'infrazione, salvo che questa non sia stata commessa all'interno della propria area di rigore. In questo caso il calcio di punizione dovrà essere battuto da un punto della linea dell'area di rigore che sia il più vicino possibile a quello dove è stata commessa l'infrazione.</li>
    <li>Sanzioni disciplinari<br>— Falli passibili di ammonizione —<br>Un calciatore deve essere ammonito con il cartellino giallo quando commette una delle seguenti infrazioni:<br>a) si rende colpevole di comportamento antisportivo;<br>b) manifesta dissenso con parole e gesti;<br>c) trasgredisce ripetutamente le Regole del Giuoco;<br>d) ritarda la ripresa del giuoco;<br>e) non rispetta la distanza prescritta quando il giuoco viene ripreso con un calcio d'angolo, una rimessa laterale, un calcio di punizione;<br>f) entra o rientra nel rettangolo di giuoco senza il permesso dell'arbitro o infrange la procedura della sostituzione;<br>g) abbandona deliberatamente il rettangolo di giuoco senza il permesso dell'arbitro.<br>Per una qualsiasi delle suddette infrazioni, viene accordato, alla squadra avversaria, un calcio di punizione indiretto da battersi nel punto in cui è stata commessa l'infrazione. Se l'infrazione è stata commessa all'interno della propria area di rigore, il calcio di punizione indiretto deve essere battuto sulla linea dell'area di rigore, nel punto più vicino a quello in cui è stata commessa l'infrazione.<br>— Falli passibili di espulsione —<br>Un calciatore deve essere espulso con il cartellino rosso quando commette una delle seguenti infrazioni:<br>h) si rende colpevole di condotta violenta;<br>i) si rende colpevole di un fallo violento di giuoco;<br>l) sputa contro un avversario o qualsiasi altra persona;<br>m) priva la squadra avversaria di una rete o di una evidente opportunità di segnare una rete, toccando deliberatamente il pallone con le mani. Questo non si applica ad un portiere all'interno della propria area di rigore (condotta gravemente sleale);<br>n) priva di una evidente opportunità di segnare una rete un avversario che si dirige verso la porta opposta, mediante un fallo punibile con un calcio di punizione diretto o un calcio di rigore (condotta gravemente<br>sleale);<br>o) usa un linguaggio offensivo, ingiurioso o minaccioso;<br>p) riceve una seconda ammonizione nella stessa gara.<br><br>Se il giuoco viene interrotto perché un calciatore viene espulso per le infrazioni (o) o (p), senza che siano state commesse ulteriori infrazioni alle Regole del Giuoco, il giuoco viene ripreso con un calcio di punizione indiretto, assegnato alla squadra avversaria, dal punto in cui è stata commessa l'infrazione.<br>Tuttavia, se l'infrazione viene commessa nella propria area di rigore, il calcio di punizione indiretto viene battuto dalla linea dell'area di rigore, nel punto più vicino a quello in cui è stata commessa l'infrazione.<br><br>—&nbsp;Provvedimenti disciplinari dopo espulsione—<br>Dopo un espulsione il giocatore dovrà saltare il turno successivo<br><br>—Condotta gravemente indisciplinata—<br>Se un giocatore si rende colpevole di una condotta gravemente indisciplinata verrà sanzionato dal Giudice sportivo con:<br>-Un numero superiore di una giornata di squalifica<br>-Radiazione del soggetto dal torneo</li>
</ol>
<p><strong>REGOLA 23 - CALCI DI PUNIZIONE</strong></p>
<ol>
    <li>Calci di punizione<br>I calci di punizione sono diretti ed indiretti.<br>Nel momento in cui viene battuto il calcio di punizione, il pallone deve essere fermo ed il calciatore che lo ha effettuato non potrà giuocarlo una seconda volta fino a quando il pallone stesso non sia stato toccato o giuocato da un altro calciatore. La distanza dal pallone alla barriera sarà di 5 passi decretati dall’arbitro.</li>
    <li>Il calcio di punizione diretto<br>Con un calcio di punizione diretto può essere segnata direttamente una rete contro la squadra che ha commesso il fallo.</li>
    <li>Il calcio di punizione indiretto<br>Con un calcio di punizione indiretto può essere segnata una rete soltanto se il pallone tocca un altro calciatore prima di entrare in porta.</li>
    <li>Posizione del calcio di punizione<br>a) Quando viene battuto un calcio di punizione, tutti i calciatori della squadra avversaria devono trovarsi ad una distanza di almeno 5 metri dal pallone prima che questo sia giuocato.<br>b) Il pallone è in giuoco dopo che è stato toccato e si muove.</li>
    <li>Infrazioni e Sanzioni<br>a) Quando un calciatore della squadra avversaria non rispetta la distanza prescritta per l'esecuzione di un calcio di punizione, il calcio di punizione deve essere ripetuto;<br>b) Se il calciatore che ha battuto il calcio di punizione tocca una seconda volta il pallone prima che questo sia stato toccato o giuocato da un altro calciatore deve essere concesso, a favore della squadra avversaria, un calcio di punizione indiretto dal punto in cui è stata commessa l'infrazione. Tuttavia, se<br>quest'ultima è stata commessa all'interno dell'area di rigore, il calcio di punizione indiretto sarà battuto dalla linea dell'area di rigore, nel punto più vicino a quello in cui l'infrazione è stata commessa;<br>c) Se la squadra che deve battere il calcio di punizione impiega più di 4 secondi per eseguirlo, sarà accordato un calcio di punizione indiretto alla squadra avversaria.</li>
    <li>Segnali<br>a) Calcio di punizione diretto: l'arbitro mantiene un braccio orizzontalmente indicando la direzione in cui il calcio deve essere battuto. Nel caso in cui il fallo venga considerato come un fallo cumulativo, l'arbitro punta verso terra con l'indice dell'altro braccio appunto per indicare, al terzo arbitro o al cronometrista, che tale fallo viene considerato come fallo cumulativo.<br>b) Calcio di punizione indiretto: l'arbitro indica un calcio di punizione indiretto alzando il suo braccio al di sopra della testa. Egli mantiene il braccio in tale posizione fino a quando il calcio di punizione non sia stato battuto ed il pallone non abbia toccato un altro calciatore o cessi di essere in giuoco.</li>
</ol>
<p><strong>REGOLA 24 - CALCIO DI RIGORE<br></strong>Un calcio di rigore viene concesso contro una squadra che commette una delle infrazioni punibili con un calcio di punizione diretto, all'interno della propria area di rigore e mentre il pallone è in giuoco.<br>Una rete può essere segnata direttamente con un calcio di rigore.<br>La durata del primo e del secondo tempo di giuoco o dei tempi supplementari deve essere prolungata per consentire l'esecuzione di un calcio di rigore.</p>
<p>1)&nbsp;&nbsp;&nbsp;&nbsp; Posizione del pallone e dei calciatori<br>a) Il pallone viene collocato sul punto del calcio di rigore<br>b) Il calciatore che batte il calcio di rigore è debitamente identificato<br>c) Il portiere difendente rimane sulla sua linea di porta, di fronte al calciatore incaricato del tiro, tra i due pali della porta, fino a quando il pallone non viene calciato.<br>d) Tutti i calciatori, tranne l'incaricato del tiro, devono posizionarsi:<br>• all'interno del rettangolo di giuoco;<br>• fuori dall'area di rigore;<br>• dietro o sulla linea immaginaria passante per il punto del rigore parallela alla linea di porta;<br>• almeno a 5 m. dal punto del calcio di rigore.</p>
<p>2)&nbsp;&nbsp;&nbsp;&nbsp; Procedura<br>La procedura è la seguente:<br>a) il calciatore che batte il calcio di rigore deve calciare in avanti il pallone;<br>b) egli non può giuocare una seconda volta il pallone fino a quando lo stesso non è stato toccato o giuocato da un altro calciatore;<br>c) il pallone è in giuoco appena è toccato e si muove in avanti;<br>d) se il calcio di rigore viene concesso allo scadere di uno dei tempi regolamentari o supplementari la gara deve essere prolungata per consentire l'esecuzione o la ripetizione di un calcio di rigore e la rete sarà considerata valida se, prima di passare tra i pali della porta e sotto la sbarra trasversale, il pallone tocca uno o entrambi i pali della porta oppure la sbarra trasversale o il portiere o una combinazione di uno o più dei suddetti elementi.</p>
<p>3)&nbsp;&nbsp;&nbsp;&nbsp; Infrazioni e Sanzioni<br>a) Se un calciatore della squadra difendente commette un'infrazione a questa Regola:<br>• il calcio di rigore dovrà essere ripetuto solo se la rete non è stata segnata;<br>• il calcio di rigore non dovrà essere ripetuto se è stata segnata una rete.<br>b) Se un compagno di squadra del calciatore incaricato del tiro commette un'infrazione a questa Regola:<br>• il calcio di rigore dovrà essere ripetuto se è stata segnata una rete<br>• il calcio di rigore non dovrà essere ripetuto se non è stata segnata una rete.<br>c) Se il calciatore che ha battuto il calcio di rigore commette un'infrazione a questa Regola, con il pallone in giuoco, alla squadra avversaria viene concesso un calcio di punizione indiretto che dovrà essere calciato dal punto in cui è stato commesso il fallo. Se il fallo è stato commesso all'interno dell'area di rigore, il calcio di punizione indiretto sarà battuto dalla linea dell'area di rigore nel punto più vicino a quello in cui l'infrazione è stata commessa.</p>
<p><strong>REGOLA 25 - RIMESSA DALLA LINEA LATERALE<br></strong>La rimessa dalla linea laterale è un modo di riprendere il giuoco. Viene battuta con le mani.<br>Una rete non può essere segnata direttamente su rimessa dalla linea laterale.</p>
<p>1)&nbsp;&nbsp;&nbsp;&nbsp; La rimessa laterale viene concessa:<br>a) quando il pallone oltrepassa interamente una linea laterale, sia a terra sia in aria, o colpisce il soffitto;<br>b) dal punto in cui ha oltrepassato la linea laterale;<br>c) alla squadra avversaria del calciatore che ha toccato per ultimo il pallone.</p>
<p>2)&nbsp;&nbsp;&nbsp;&nbsp; Posizione del pallone e dei calciatori<br>a) Il pallone deve essere fermo sulla (o dietro) linea laterale e deve essere rimesso in giuoco in qualsiasi direzione.<br>b) I calciatori della squadra difendente si devono trovare ad almeno 5 m. dal pallone.</p>
<p>3)&nbsp;&nbsp;&nbsp;&nbsp; Procedura<br>La procedura è la seguente:<br>a) Il calciatore che esegue la rimessa dalla linea laterale deve farlo entro 4 secondi dal momento in cui viene in possesso del pallone;<br>b) il calciatore che effettua la rimessa dalla linea laterale non può giuocare il pallone una seconda volta prima che sia toccato o giocato da un altro calciatore;<br>c) il pallone è in giuoco immediatamente dopo che è stato calciato o toccato.</p>
<p>4)&nbsp;&nbsp;&nbsp;&nbsp; Infrazioni e Sanzioni<br>a) Viene accordato un calcio di punizione indiretto alla squadra avversaria se il calciatore che effettua la rimessa dalla linea laterale giuoca il pallone una seconda volta prima che sia stato toccato o giocato da un altro calciatore. Il calcio di punizione indiretto viene eseguito dal punto in cui è stata commessa l'infrazione, salvo che ciò sia avvenuto nell'area di rigore, nel qual caso il calcio di punizione indiretto sarà battuto dalla linea dell'area di rigore, dal punto più vicino a quello in cui è stato commesso l'infrazione.<br>b) La rimessa dalla linea laterale viene ripetuta da un calciatore della squadra avversaria se:<br>• la rimessa dalla linea laterale non è stata effettuata regolarmente;<br>• la rimessa dalla linea laterale viene effettuata da un punto diverso da quello in cui il pallone ha oltrepassato la linea laterale;<br>• la rimessa dalla linea laterale non è stata effettuata entro 4 secondi dal momento in cui il calciatore è entrato in possesso del pallone.<br><br>La rimessa dal fondo è un modo di riprendere il giuoco.<br>Una rete non può essere segnata direttamente su rimessa dal fondo.</p>
<p><strong>REGOLA 26 - RIMESSA DAL FONDO</strong></p>
<p>1)&nbsp;&nbsp;&nbsp;&nbsp; La rimessa dal fondo viene concessa<br>a) quando il pallone, toccato per ultimo da un calciatore della squadra attaccante, oltrepassa interamente la linea di porta, sia a terra che in aria, e non è stata segnata una rete come prescritto dalla Regola 7.</p>
<p>2)&nbsp;&nbsp;&nbsp;&nbsp; Procedura<br>La procedura è la seguente:<br>a) Il portiere lancia il pallone con i piedi dalla sua area piccola (la più vicina alla porta);<br>b) I calciatori della squadra avversaria dovranno rimanere al di fuori dell'area di rigore finché il pallone non è in giuoco;<br>c) il portiere non dovrà giuocare il pallone una seconda volta finché questo non sia stato toccato o giuocato da un altro calciatore;<br>d) il pallone sarà in giuoco quando sarà uscito completamente fuori dall'area di rigore.</p>
<p>3)&nbsp;&nbsp;&nbsp;&nbsp; Infrazione e Sanzioni<br>a) se il pallone non viene lanciato direttamente fuori dall'area di rigore, viene ripetuta la rimessa dal fondo;<br>b) se, dopo che il pallone è in giuoco, il portiere tocca il pallone una seconda volta, prima che sia stato toccato o giuocato da un altro calciatore, viene concesso un calcio di punizione indiretto alla squadra avversaria dal punto in cui è stata commessa l'infrazione, salvo che ciò sia avvenuto nell'area di rigore,<br>nel qual caso il calcio di punizione indiretto sarà battuto dalla linea dell'area di rigore, dal punto più vicino a quello in cui è stato commesso il fallo.<br>c) se il pallone è giocato dopo 4 secondi, contati dal momento in cui il portiere entra in possesso del pallone, sarà accordato un calcio di punizione indiretto alla squadra avversaria che sarà battuto sulla linea dell'area di rigore nel punto più vicino a quello in cui l'infrazione è stata commessa.</p>
<p><strong>REGOLA 27 - CALCIO D'ANGOLO<br></strong>Il calcio d'angolo è un modo di riprendere il giuoco.<br>Una rete può essere segnata direttamente su calcio d'angolo, ma soltanto contro la squadra avversaria.</p>
<p>1)&nbsp;&nbsp;&nbsp;&nbsp; Viene concesso un calcio d'angolo<br>a) quando il pallone toccato per ultimo da un calciatore della squadra difendente, oltrepassa interamente la linea di porta, sia in terra sia in aria, e non è stata segnata una rete.</p>
<p>2)&nbsp;&nbsp;&nbsp;&nbsp; Procedura<br>La procedura è la seguente:<br>a) il pallone deve essere collocato all'interno dell'area d'angolo;<br>b) i calciatori della squadra avversaria devono rimanere a 5 m. almeno dal pallone finché esso non è in giuoco;<br>c) il pallone viene calciato da un calciatore della squadra attaccante;<br>d) il pallone è in giuoco quando viene toccato e si muove;<br>e) il calciatore che ha battuto il calcio d'angolo non può giuocare una seconda volta il pallone fino a quando lo stesso non sia stato toccato o giuocato da un altro calciatore.</p>
<p>3)&nbsp;&nbsp;&nbsp;&nbsp; Infrazioni e Sanzioni</p>
<p>Alla squadra avversaria viene assegnato un calcio di punizione indiretto quando:<br>• il calciatore che ha battuto il calcio d'angolo giuoca una seconda volta il pallone prima che questo sia stato toccato o giuocato da un altro calciatore. Il calcio di punizione indiretto viene battuto dal punto in cui è stata commessa l'infrazione;<br>• il calcio d'angolo non viene battuto entro 4 secondi dal momento in cui il calciatore che lo deve battere entra in possesso del pallone ed il calcio di punizione indiretto viene eseguito dall'arco d'angolo.</p>
<p><strong>REGOLA 28 – RECLAMI PER PROVVEDIMENTI DISCIPLINARI<br></strong><span>Il presente regolamento viene integralmente accettato dal capitano della squadra al momento dell'iscrizione.&nbsp;</span><br>Come già anticipato nella premessa di tale regolamento, l'Asd Arend non è responsabile dei provvedimenti disciplinari. Questi sono, in qualsiasi caso, di responsabilità del Comitato Disciplinare.</p>
<p>Le squadre che vorranno richiedere un reclamo ad eventuali provvedimenti ritenuti ingiustificati o eccessivi dovranno inviare un reclamo in forma scritta all indirizzo&nbsp;<a href="mailto:disciplinare@asdarend.it">disciplinare@asdarend.it</a>&nbsp;che si prodigherà a inoltrare la mail al Giudice di Competenza.&nbsp;<br>Ogni reclamo non potrà esser presentato oltre le 24 ore dalla pubblicazione del Comunicato Ufficiale.</p>
<p>La stessa procedura dovrà esser rispettata qualora una società avesse riscontrato “problematiche” nella gara svolta, avvertendo entro il 25' minuto di voler muovere ricorso al direttore di gara.<br>Anche in questo caso il limite d'attesa per il reclamo è di 24ore dalla fine della gara incriminata.</p>
<p><strong>REGOLA 29 - TERMINI D'ACCETTAZIONE REGOLAMENTO<br></strong><span>Il presente regolamento viene integralmente accettato dal capitano della squadra al momento dell'iscrizione.&nbsp;</span><br>Si precisa che il regolamento non potrà avere cambiamenti fino alla fine del torneo.<br>L'organizzazione si farà carico di tutti gli argomenti non contemplati nel suddetto regolamento che ,se necessario ,verrà aggiornato previa comunicazione a tutti i capitani del torneo</p>						<p></p>
