/*
 * PanelEnvios.java
 *
 * Created on 22 de mayo de 2008, 22:26
 */

package Paneles;

import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

import controladores.ControladorPanelSolDis;
import GUI.MenuPrincipal;

/**
 *
 * @author  Administrador
 */
public class PanelEnvios extends javax.swing.JPanel {

    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private MenuPrincipal ref;
    private ControladorPanelSolDis cm;
    
    /** Creates new form PanelEnvios */
    public PanelEnvios(MenuPrincipal menu) {
        initComponents();
        DefaultMutableTreeNode abuelo = new DefaultMutableTreeNode("Articulos");
        DefaultTreeModel modelo = new DefaultTreeModel(abuelo);
        treeArticulos = new JTree(modelo);
        DefaultMutableTreeNode padre = new DefaultMutableTreeNode("Solicitados");
        DefaultMutableTreeNode tio = new DefaultMutableTreeNode("Pendientes");
        modelo.insertNodeInto(padre,abuelo,0);
        modelo.insertNodeInto(tio, abuelo, 1);
        jScrollPane2.setViewportView(treeArticulos);
        this.ref = menu;
        this.cm = new ControladorPanelSolDis(ref.getVistaPadre().getModelo(),ref.getVistaPadre());
    }
    
    public void update()
    {
    	
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBoxTiendas = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeArticulos = new javax.swing.JTree();
        buttonCargar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEnviar = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePendientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonEnviarTienda = new javax.swing.JButton();
        buttonEnviarFabrica = new javax.swing.JButton();

        jLabel1.setText("Tienda");

        comboBoxTiendas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tienda 1", "Tienda 2", "Tienda 3" }));
        comboBoxTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTiendasActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(treeArticulos);

        buttonCargar.setText("Cargar");
        buttonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCargarActionPerformed(evt);
            }
        });

        tableEnviar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Art.", "Descripcion", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableEnviar);

        tablePendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Art.", "Descripcion", "Cantidad", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablePendientes);

        jLabel2.setText("Articulos Pendientes");

        jLabel3.setText("Articulos a Enviar");

        buttonEnviarTienda.setText("Enviar Tienda");
        buttonEnviarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnviarTiendaActionPerformed(evt);
            }
        });

        buttonEnviarFabrica.setText("Enviar Fabrica");
        buttonEnviarFabrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnviarFabricaActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel1)
                                .add(30, 30, 30)
                                .add(comboBoxTiendas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(73, 73, 73)
                                .add(jLabel2))
                            .add(layout.createSequentialGroup()
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(93, 93, 93)
                                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 212, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(46, 46, 46)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 253, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(buttonCargar)
                        .add(111, 111, 111)
                        .add(buttonEnviarFabrica)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 178, Short.MAX_VALUE)
                        .add(buttonEnviarTienda)
                        .add(168, 168, 168))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(72, 72, 72)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(comboBoxTiendas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(44, 44, 44)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(67, 67, 67)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(jLabel3))
                        .add(38, 38, 38)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 176, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(29, 29, 29)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(buttonCargar)
                            .add(buttonEnviarTienda)
                            .add(buttonEnviarFabrica))))
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

private void buttonCargarActionPerformed(java.awt.event.ActionEvent evt) {                                             
// Cargar solicitud en tablas
    
    	int ret = ((ControladorPanelSolDis)this.ref.getVistaPadre().getControlador()).doGetTestNumber();
    	JOptionPane.showMessageDialog(null, String.valueOf(ret));
    	/*DefaultMutableTreeNode node = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
//this.cm.doGetSolicitudes(tienda);
        if (node == null) JOptionPane.showMessageDialog(this, "Debe elegir un tipo de articulo.",Constantes.APPLICATION_NAME,JOptionPane.ERROR_MESSAGE);

        String nodeInfo = (String)node.getUserObject();
        Vector<Articulo> ret = null;//((ControladorMain)ref.getVistaPadre().getControlador()).doGetArticulosEnvio((String)jComboBox1.getSelectedItem(),nodeInfo);
        
        if(ret != null)
        {
            if(nodeInfo.equalsIgnoreCase("Solicitados"))
            {
                //cargar en tabla solicitados
            }
            else
            {
                //cargar en tabla pendientes
            }
        }
        else JOptionPane.showMessageDialog(this, "No se encontraron articulos",Constantes.APPLICATION_NAME,JOptionPane.ERROR_MESSAGE);*/

}                                            

private void comboBoxTiendasActionPerformed(java.awt.event.ActionEvent evt) {                                                
  //Combo de seleccion de tienda
}                                               

private void buttonEnviarFabricaActionPerformed(java.awt.event.ActionEvent evt) {                                                    
// TODO add your handling code here:
}                                                   

private void buttonEnviarTiendaActionPerformed(java.awt.event.ActionEvent evt) {                                                   
// TODO add your handling code here:
}                                                  


    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonCargar;
    private javax.swing.JButton buttonEnviarFabrica;
    private javax.swing.JButton buttonEnviarTienda;
    private javax.swing.JComboBox comboBoxTiendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableEnviar;
    private javax.swing.JTable tablePendientes;
    private javax.swing.JTree treeArticulos;
    // End of variables declaration                   

}
