/*
 * PanelNewArt.java
 *
 * Created on 22 de mayo de 2008, 22:44
 */

package Paneles;

import javax.swing.JOptionPane;

import Varios.Constantes;
import Vistas.VistaNewArt;

import GUI.FileChooser;
import GUI.MenuPrincipal;

/**
 *
 * @author  Administrador
 */
public class PanelNewArt extends javax.swing.JPanel {

	/** Creates new form PanelNewArt */
	private static final long serialVersionUID = 1L;
    private MenuPrincipal ref;
    private VistaNewArt vistaNewArt;
    
    public PanelNewArt(MenuPrincipal m, VistaNewArt vista) {
        initComponents();
        this.ref = m;
        this.vistaNewArt = vista;
    }
    
    public void update()
    {
    	
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableArticulo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buttonCargarXML = new javax.swing.JButton();
        buttonGuardar = new javax.swing.JButton();

        tableArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Atributo", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableArticulo.getTableHeader().setResizingAllowed(false);
        tableArticulo.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableArticulo);

        jLabel1.setText("Nuevo Articulo");

        buttonCargarXML.setText("Cargar Articulo");
        buttonCargarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCargarXMLActionPerformed(evt);
            }
        });

        buttonGuardar.setText("Guardar");
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(35, 35, 35)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(buttonCargarXML)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 156, Short.MAX_VALUE)
                        .add(buttonGuardar))
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 332, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(672, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createSequentialGroup()
                .add(125, 125, 125)
                .add(jLabel1)
                .addContainerGap(844, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(37, 37, 37)
                .add(jLabel1)
                .add(39, 39, 39)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .add(50, 50, 50)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buttonCargarXML)
                    .add(buttonGuardar))
                .add(104, 104, 104))
        );
    }// </editor-fold>                        

private void buttonCargarXMLActionPerformed(java.awt.event.ActionEvent evt) {                                                
// TODO add your handling code here:
        chooser = new FileChooser(ref,true,ref.getDefaltXmlPath());
        String a = chooser.getPath();
        String b = chooser.getFile();
        
        if(a.equals(""))JOptionPane.showMessageDialog(this,"Debe ingresar la ubicacion del archivo XML.\n", Constantes.APPLICATION_NAME, JOptionPane.ERROR_MESSAGE);
        else
        {
            //Cargar los table
            ref.getJTextArea1().append("Archivo Cargado\n");
            String url = chooser.getPath();
           // ((ControladorMain)ref.getVistaPadre().getControlador()).doMostrarSolicitud(url);
        }
}                                               

private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                              
// TODO add your handling code here:
}                                             


    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonCargarXML;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableArticulo;
    private FileChooser chooser;
    // End of variables declaration                   

	public VistaNewArt getVistaNewArt() {
		return vistaNewArt;
	}

	public void setVistaNewArt(VistaNewArt vistaNewArt) {
		this.vistaNewArt = vistaNewArt;
	}

}
