/*
 * PanelSolDist.java
 *
 * Created on 22 de mayo de 2008, 22:58
 */

package Paneles;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

import GUI.Dialogo3Opciones;
import GUI.FileChooser;
import GUI.MenuPrincipal;
import VO.ArticuloAEnviarVO;
import VO.ArticuloAFabricarVO;
import VO.ArticuloHeaderVO;
import VO.ArticuloPedidoVO;
import VO.CentroDistribucionVO;
import VO.FabricaVO;
import VO.SolicitudDistribucionVO;
import Varios.Constantes;
import Varios.XMLWrapper;
import Vistas.VistaSolDis;
import controladores.ControladorPanelSolDis;

/**
 * 
 * @author Administrador
 */
public class PanelSolDist extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;

	private String urlXML;

	private boolean cargarTable;

	private MenuPrincipal ref;
	private ArrayList<FabricaVO> fabricas;
	private SolicitudDistribucionVO solDisVO;

	private VistaSolDis vistaSolDis;

	/** Creates new form PanelSolDist */
	public PanelSolDist(MenuPrincipal mn, VistaSolDis vista) {
		initComponents();
		this.buttonGuardarPedido.setEnabled(false);
		this.comboFabrica.setEnabled(false);
		this.ref = mn;
		this.vistaSolDis = vista;
		tableArticulos.getModel().addTableModelListener(
				new TableModelListener() {
					public void tableChanged(TableModelEvent e) {
						if (e.getColumn() > -1)
							validateTable();
					}
				});
		ArrayList<FabricaVO> fabricas = this.ref.getVistaSolDis().getModelo().getFabricas();
		this.fabricas = fabricas;
		for (int i = 0 ; i < fabricas.size() ; i++ ){
			FabricaVO fab = fabricas.get(i);
			((DefaultComboBoxModel)comboFabrica.getModel()).addElement(fab.getNombreFabrica());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonCargarXML = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableArticulos = new javax.swing.JTable();
        buttonGuardarPedido = new javax.swing.JButton();
        labelValidacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboFabrica = new javax.swing.JComboBox();

        jLabel1.setText("Solicitud de distribucion");

        buttonCargarXML.setText("Cargar XML");
        buttonCargarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCargarXMLActionPerformed(evt);
            }
        });

        tableArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Numero Solicitud", "Tienda", "Codigo Art.", "Descripcion", "Cantidad Pedida", "Stock Actual", "Cantidad a Enviar"
            }
        ) {
			private static final long serialVersionUID = -7276347293843632059L;
			Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableArticulos.setRowSelectionAllowed(false);
        tableArticulos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableArticulos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableArticulos);

        buttonGuardarPedido.setText("Guardar Pedido");
        buttonGuardarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarPedidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Fabrica");

        comboFabrica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(766, 766, 766)
                        .add(labelValidacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 705, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(jLabel1)
                                .add(96, 96, 96)
                                .add(buttonCargarXML))
                            .add(buttonGuardarPedido)
                            .add(layout.createSequentialGroup()
                                .add(jLabel2)
                                .add(71, 71, 71)
                                .add(comboFabrica, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(buttonCargarXML))
                        .add(29, 29, 29)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 204, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(155, 155, 155)
                        .add(labelValidacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(comboFabrica, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 34, Short.MAX_VALUE)
                .add(buttonGuardarPedido)
                .add(70, 70, 70))
        );
	}// </editor-fold>

	private void buttonGuardarPedidoActionPerformed(
			java.awt.event.ActionEvent evt) {
		((ControladorPanelSolDis) vistaSolDis.getControlador())
				.doCargarXML(false);
	}

	private void buttonCargarXMLActionPerformed(java.awt.event.ActionEvent evt) {
		// Carga archivo XML
		chooser = new FileChooser(ref, true, ref.getDefaltXmlPath());
		urlXML = chooser.getPath();
		if (urlXML.equals(""))
			JOptionPane.showMessageDialog(this,
					"Debe ingresar la ubicacion del archivo XML.\n",
					Constantes.APPLICATION_NAME, JOptionPane.ERROR_MESSAGE);
		else {
			// Cargar los table
			((ControladorPanelSolDis) vistaSolDis.getControlador())
			.doCargarXML(true);
		}
	}

	private void cargarTable(SolicitudDistribucionVO solDisVO,
			ArrayList<Long> codigos, ArrayList<String> descripciones,
			ArrayList<Integer> stocks) {
		Iterator iterador = (Iterator) solDisVO.getArticulosPedidos()
				.iterator();
		for (int i = 0; i < solDisVO.getArticulosPedidos().size(); i++) {
			((DefaultTableModel) tableArticulos.getModel())
					.addRow(new Object[] {
							solDisVO.getNumero(),
							solDisVO.getTienda().getNombreTienda(),
							codigos.get(i).toString(),
							descripciones.get(i).toString(),
							((ArticuloPedidoVO) iterador.next()).getCantidad(),
							stocks.get(i).toString(), 0 });
		}
	}

	private void validateTable() {
		//ARREGLAR MAS TARDE
		boolean grabar = true;
		int fabricar = 0;
		int cantCeros = 0;

		for (int i = 0; i < tableArticulos.getModel().getRowCount(); i++) {
			int valor = Integer.parseInt(tableArticulos.getModel().getValueAt(
					i, 6).toString());
			int pedido = Integer.parseInt(tableArticulos.getModel().getValueAt(
					i, 4).toString());
			int stock = Integer.parseInt(tableArticulos.getModel().getValueAt(
					i, 5).toString());

			if (valor == 0)
				cantCeros++;
			if ((valor < 0) || (valor > pedido)) {
				grabar = false;
				if (valor > pedido){
					tableArticulos.getModel().setValueAt(0,i, 6);
					JOptionPane.showMessageDialog(this,
							"El valor ingresado es mayor al pedido.",
							Constantes.APPLICATION_NAME,
							JOptionPane.ERROR_MESSAGE);
					break;
				}
				tableArticulos.getModel().setValueAt(0,i, 6);
				JOptionPane.showMessageDialog(this,
						"El valor ingresado tiene que ser un numero positivo.",
						Constantes.APPLICATION_NAME,
						JOptionPane.ERROR_MESSAGE);
				break;
			}
			if(stock<valor){
				tableArticulos.getModel().setValueAt(0,i, 6);
				JOptionPane.showMessageDialog(this,
						"El valor ingresado es mayor al stock actual.",
						Constantes.APPLICATION_NAME,
						JOptionPane.ERROR_MESSAGE);
				break;
			}
			if(pedido>valor){
				fabricar++;
			}
			if(fabricar>0){
				this.comboFabrica.setEnabled(true);
			}else{
				this.comboFabrica.setEnabled(false);
			}
				
		}
		if ((grabar) && (cantCeros < tableArticulos.getModel().getRowCount())) {
			buttonGuardarPedido.setEnabled(true);
			labelValidacion.setText("OK");
			labelValidacion.setForeground(Color.GREEN);
		} else {
			buttonGuardarPedido.setEnabled(false);
			labelValidacion.setForeground(Color.RED);
			if (!grabar)
				labelValidacion
						.setText("Hay errores en los valores ingresados");
			else
				labelValidacion.setText("Debe ingresar valores.");
		}
	}

	public void update() {
		// aca hay que poner las llamadas a la business delegate
		// hay que arreglar LA FECHA DE SOLDIS
		if (cargarTable) {
			XMLWrapper xml = new XMLWrapper();
			solDisVO = (SolicitudDistribucionVO) xml.parseXMLSD(urlXML);
			if(((ControladorPanelSolDis)vistaSolDis.getControlador()).doExisteSolicitudDeDistribucion(solDisVO.getNumero())){
				vaciarTabla();
				ref.getJTextArea1().append("Solicitud de Distribucion 'existente' en el Centro de Distribucion \n");
				this.buttonCargarXML.setEnabled(true);
				this.buttonGuardarPedido.setEnabled(false);
				JOptionPane.showMessageDialog(this,"La Solicitud de Distribucion ya existe",Constantes.APPLICATION_NAME,JOptionPane.ERROR_MESSAGE);
			}else{
				solDisVO.setFechaEmision(ref.getDate());
				ArrayList<Long> codigos = new ArrayList<Long>();
				int idMax = this.ref.getVistaSolDis().getModelo().getNextId();
				Iterator arts = (Iterator) solDisVO.getArticulosPedidos().iterator();
				ArrayList<ArticuloPedidoVO> artsVO = new ArrayList<ArticuloPedidoVO>();
				while (arts.hasNext()) {
					ArticuloPedidoVO artVO = ((ArticuloPedidoVO) arts.next());
					idMax++;
					artVO.setIdAP(idMax);
					codigos.add(artVO.getArt().getCodigo());
					artsVO.add(artVO);
				}
				solDisVO.setArticulosPedidos(artsVO);
				ArrayList<String> descripciones = this.ref.getVistaSolDis()
						.getModelo().getDescripciones(codigos);
				ArrayList<Integer> stocks = this.ref.getVistaSolDis().getModelo().getStocks(codigos) ;
				CentroDistribucionVO centroVO = this.ref.getVistaSolDis().getModelo().getCentro();
				solDisVO.setCdVO(centroVO);
				cargarTable(solDisVO, codigos, descripciones, stocks);
				ref.getJTextArea1().append("Archivo Cargado\n");
			}
		} else {
			// Falta generar las solicitudes
			Collection<ArticuloAFabricarVO> artiAFab = (Collection<ArticuloAFabricarVO>) articulosFabricarDeTabla();
			Collection<ArticuloAEnviarVO> artiAEnv = (Collection<ArticuloAEnviarVO>) articulosEnviarDeTabla();
			if((!artiAFab.isEmpty()) && ( comboFabrica.getSelectedItem().toString().equals(""))){
				JOptionPane.showMessageDialog(this,
						"Debe seleccionar una fabrica.\n",
						Constantes.APPLICATION_NAME, JOptionPane.ERROR_MESSAGE);
			}else{
				((ControladorPanelSolDis) vistaSolDis.getControlador()).doGuardarSolicitud(solDisVO);
				((ControladorPanelSolDis) vistaSolDis.getControlador()).doGuardarArticulosAEnviar(artiAEnv);
				((ControladorPanelSolDis) vistaSolDis.getControlador()).doGuardarArticulosAFabricar(artiAFab);
				((ControladorPanelSolDis) vistaSolDis.getControlador()).doActualizarStocks(artiAEnv);
				vaciarTabla();
				ref.getJTextArea1().append("Solicitudes Guardadas\n");
				new Dialogo3Opciones("Operacion concretada", this).setVisible(true);	
			}
		}
	}

	/*
	 * Falta completar la linea comentada
	 * 
	 * 
	 */
	public Collection<ArticuloAEnviarVO> articulosEnviarDeTabla() {
		Collection<ArticuloAEnviarVO> art = new ArrayList<ArticuloAEnviarVO>();
		ArticuloHeaderVO arti;
		int idMax = this.ref.getVistaSolDis().getModelo().getNextIdAEnv();
		for (int i = 0; i < tableArticulos.getRowCount(); i++) {
			long cod = (Long
					.parseLong((String) ((DefaultTableModel) tableArticulos
							.getModel()).getValueAt(i, 2)));
			arti = ((ControladorPanelSolDis) vistaSolDis.getControlador())
					.doGetArticulo(cod);
			ArticuloAEnviarVO aEnv = new ArticuloAEnviarVO();
			idMax++;
			aEnv.setIdAAE(idMax);
			aEnv.setArt(arti);
			aEnv.setCantidadAEnviar(Integer.parseInt((((DefaultTableModel) tableArticulos.getModel()).getValueAt(i, 6)).toString()));
			aEnv.setSolDis(solDisVO);
			// aEnv.setIdAAE();
			art.add(aEnv);
		}
		return art;
	}

	/*
	 * Falta completar la linea comentada
	 * 
	 * la fabrica se va obtener de un combo
	 */
	public Collection<ArticuloAFabricarVO> articulosFabricarDeTabla() {
		Collection<ArticuloAFabricarVO> art = new ArrayList<ArticuloAFabricarVO>();
		ArticuloHeaderVO arti;
		int idMax = this.ref.getVistaSolDis().getModelo().getNextIdAFab();
		FabricaVO fabr = null;
		for(int i=0 ; i< fabricas.size() ; i++){
			if(((FabricaVO)fabricas.get(i)).getNombreFabrica().equals(comboFabrica.getSelectedItem().toString())){
				fabr = fabricas.get(i);
			}
		}
		for (int i = 0; i < tableArticulos.getRowCount(); i++) {
			int ped = Integer.parseInt((((DefaultTableModel) tableArticulos
					.getModel()).getValueAt(i, 4)).toString());
			int sel = Integer.parseInt((((DefaultTableModel) tableArticulos
					.getModel()).getValueAt(i, 6)).toString());
			if (ped > sel) {
				long cod = (Long
						.parseLong((String) ((DefaultTableModel) tableArticulos
								.getModel()).getValueAt(i, 2)));
				arti = ((ControladorPanelSolDis) vistaSolDis.getControlador())
						.doGetArticulo(cod);
				ArticuloAFabricarVO aFab = new ArticuloAFabricarVO();
				aFab.setArt(arti);
				aFab.setCantidadPedida(ped - sel);
				aFab.setCantidadRecibida(0);
				aFab.setCantidadAFabricar(0);
				// aFab.setFabrica()
				// aFab.setIdAAF();
				idMax++;
				aFab.setIdAAF(idMax);
				aFab.setSol(solDisVO);
				aFab.setFabrica(fabr);
				art.add(aFab);
			} else {
				ref.getJTextArea1().append("Error al cargar los articulos a fabricar, xq lo seleccionado es mayor que lo pedido\n");
			}
		}
		return art;
	}

	public void vaciarTabla() {
		((DefaultTableModel)tableArticulos.getModel()).getDataVector().removeAllElements();
	}

	// Variables declaration - do not modify
	private javax.swing.JButton buttonCargarXML;

	private javax.swing.JButton buttonGuardarPedido;

	private javax.swing.JLabel jLabel1;

	private javax.swing.JLabel jLabel2;

	private javax.swing.JScrollPane jScrollPane1;

	private javax.swing.JLabel labelValidacion;

	private javax.swing.JComboBox comboFabrica;

	private javax.swing.JTable tableArticulos;

	private FileChooser chooser;

	// End of variables declaration

	public boolean getCargarTable() {
		return cargarTable;
	}

	public void setCargarTable(boolean cargarTable) {
		this.cargarTable = cargarTable;
	}

	public ArrayList<FabricaVO> getFabricas() {
		return fabricas;
	}

	public void setFabricas(ArrayList<FabricaVO> fabricas) {
		this.fabricas = fabricas;
	}

	public void setRef(MenuPrincipal ref) {
		this.ref = ref;
	}

	public MenuPrincipal getRef() {
		return ref;
	}

}
